on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven Build
        run: mvn install -DskipTests

  Test:
    runs-on : ubuntu-latest
    needs: Build
    steps:
      - name: Maven Test
        run: mvn test
