on:
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven Build
        run: mvn install -DskipTests

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven Test
        run: mvn test

  Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Test checkstyle
        run: mvn test checkstyle:checkstyle

  Foo:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Create Foo dir
        run: mkdir Foo
