on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven Build
        run: mvn install -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: products_app_artifact
          path: target/*.jar

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven Tes
        run: mvn test

  Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Test checkstyle
        run: mvn test checkstyle:checkstyle

  Foo:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Create Foo dir
        run: mkdir Foo

  Post-check:
    runs-on: ubuntu-latest
    needs: [Build, Test, Scan]
    steps:
      - name: Failure notif
        if: failure()
        run: echo "❌ failed!"

