on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven Build
        run: mvn install -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: products_app_artifact
          path: target/*.jar

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven Test
        run: mvn tes

  Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Test checkstyle
        run: mvn test checkstyle:checkstyle

  Foo:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Create Foo dir
        run: mkdir Foo

  Post-check:
    if: always()
    runs-on: ubuntu-latest
    needs: [Build, Test, Scan]
    steps:
      - name: Summarize Results
        run: |
          echo "Build result: ${{ needs.Build.result }}"
          echo "Test result: ${{ needs.Test.result }}"
          echo "Scan result: ${{ needs.Scan.result }}"          

      - name: Failure notif
        if: |
          needs.Build.result == 'failure' ||
          needs.Test.result == 'failure' ||
          needs.Scan.result == 'failure'
        run: echo "❌ failed!"

